;;; init.el -*- lexical-binding: t; -*-

;; DO NOT EDIT THIS FILE DIRECTLY
;; This is a file generated from a literate programing source file located at
;; https://gitlab.com/zzamboni/dot-doom/-/blob/master/doom.org
;; You should make any changes there and regenerate it from Emacs org-mode
;; using org-babel-tangle (C-c C-v t)

;; This file controls what Doom modules are enabled and what order they load
;; in. Remember to run 'doom sync' after modifying it!

;; NOTE Press 'SPC h d h' (or 'C-h d h' for non-vim users) to access Doom's
;;      documentation. There you'll find a "Module Index" link where you'll find
;;      a comprehensive list of Doom's modules and what flags they support.

;; NOTE Move your cursor over a module's name (or its flags) and press 'K' (or
;;      'C-c c k' for non-vim users) to view its documentation. This works on
;;      flags as well (those symbols that start with a plus).
;;
;;      Alternatively, press 'gd' (or 'C-c c d') on a module to browse its
;;      directory (for easy access to its source code).

;;; Pre-init
;; This is so that I don't accidentally start Emacs as a daemon.
(when (daemonp) (kill-emacs))

;;;; PGTK

;; You should be able to use input methods since GtkIMContext is enabled by
;; default. If you don't like GtkIMContext, you can disable it by writing as
;; follows in ~/.emacs: pgtk-use-im-context disable gtk im modules for
;; emacs-pgtk, add "Emacs*UseXIM: false" to ~/.Xresources to disable xim
(if (eq window-system 'pgtk)
    (pgtk-use-im-context nil))

(when (boundp 'pgtk-use-im-context-on-new-connection)
  (setq pgtk-use-im-context-on-new-connection nil))

;;;; Termux

(setq-default root-path "/")

(defvar IS-TERMUX
  (string-suffix-p "Android" (string-trim (shell-command-to-string "uname -a"))))

(when IS-TERMUX
  (setq root-path "/data/data/com.termux/files/"))

;;;; android gui emacs

;; 2025-04-28
(when (string-equal system-type "android")
  (when (display-graphic-p) ; gui
    ;; Add Termux binaries to PATH environment
    ;; It is important that termuxpath is prepended, not appended.
    ;; Otherwise we will get Androids incompatible diff executable, instead of the one in Termux.
    (let ((termuxpath "/data/data/com.termux/files/usr/bin"))
      (setenv "PATH" (format "%s:%s" termuxpath
                             (getenv "PATH")))
      (push termuxpath exec-path)
      (push "~/.config/emacs/bin" exec-path))
    )
  )

;;;; Modules

(doom! :input
       :completion
       (corfu +orderless) ; +icons
       vertico

       :ui
       doom              ; what makes DOOM look the way it does
       doom-dashboard    ; a nifty splash screen for Emacs
       hl-todo           ; highlight TODO/FIXME/NOTE/DEPRECATED/HACK/REVIEW/XXX/BUG
       ;; indent-guides     ; highlighted indent columns
       modeline          ; snazzy, Atom-inspired modeline, plus API
       ophints           ; highlight the region an operation acts on
       (popup +defaults) ; tame sudden yet inevitable temporary windows
       ;; (smooth-scroll +interpolate) ; So smooth you won't believe it's not butter

       ;; treemacs          ; a project drawer, like neotree but cooler
       vc-gutter         ; vcs diff in the fringe
       (window-select +numbers) ; visually switch windows
       workspaces        ; tab emulation, persistence & separate workspaces
       zen               ; distraction-free coding or writing

       :editor
       file-templates    ; auto-snippets for empty files
       fold              ; (nigh) universal code folding
       format            ; automated prettiness
       multiple-cursors  ; editing in many places at once
       rotate-text       ; cycle region at point between text candidates
       snippets          ; my elves. They type so I don't have to
       ;;word-wrap         ; soft wrapping with language-aware indent

       (evil +everywhere); come to the dark side, we have cookies

       :emacs
       dired             ; making dired pretty [functional]
       electric          ; smarter, keyword-based electric-indent
       eww               ; the internet is gross
       ibuffer           ; +icons - interactive buffer management
       undo              ; persistent, smarter undo for your inevitable mistakes
       vc                ; version-control and Emacs, sitting in a tree

       :term
       eshell ; the elisp shell that works everywhere
       (:if (not (memq system-type '(cygwin android windows-nt ms-dos))) vterm) ; the best terminal emulation in Emacs

       :checkers
       ;; (syntax +flymake) ; tasing you for every semicolon you forget
       ;; spell +flyspell ; +hunspell - tasing you for misspelling mispelling
       ;; grammar           ; tasing grammar mistake every you make
       :tools
       biblio
       ;; debugger ; FIXME stepping through code, to help you add bugs
       ;; (:unless IS-TERMUX (direnv))

       (eval +overlay)     ; run code, run (also, repls)
       ;; lookup
       ;; (lsp +eglot)

       ;; magit ; +forge a git porcelain for Emacs

       ;; make              ; run make tasks from Emacs
       ;;pass              ; password manager for nerds
       ;; (:unless IS-TERMUX (pdf)) ; pdf enhancements
       ;; (:unless IS-TERMUX (prodigy)) ;; FIXME managing external services & code builders
       ;;terraform         ; infrastructure as code
       ;;tmux              ; an API for interacting with tmux
       ;; tree-sitter ;; syntax and parsing, sitting in a tree...
       ;; upload            ; map local to remote projects via ssh/ftp

       :os
       (:if IS-MAC macos)  ; improve compatibility with macOS
       tty                 ; improve the terminal Emacs experience

       :lang
       ;; (clojure +lsp) ; java with a lisp
       data              ; config/data formats
       emacs-lisp        ; drown in parentheses
       json  ; At least it ain't XML
       ;; (javascript +lsp) ;; all(hope(abandon(ye(who(enter(here))))))
       (latex +cdlatex +latexmk)    ; writing papers in Emacs has never been so fun
       markdown          ; writing docs for people to ignore
       (org                         ; organize your plain life in plain text
        +hugo                     ; use Emacs for hugo blogging
        +jupyter                    ; ipython/jupyter support for babel
        +pandoc                     ; export-with-pandoc support
        +gnuplot                    ; who doesn't like pretty pictures
        +present                    ; using org-mode for presentations
        +contacts
        +journal
        ;; +pretty
        ;; +noter                      ; enhanced PDF notetaking
        ;; +pomodoro                 ; be fruitful with the tomato technique
        )                     ; wander around notes
       ;; sh                ; she sells {ba,z,fi}sh shells on the C xor
       ;; python  ; +lsp +pyright +conda - beautiful is better than ugly
       ;; racket ; a DSL for DSLs
       ;; (scheme +mit) ;; +racket ; a fully conniving family of lisps
       ;; web ; the tubes
       ;; yaml ; JSON, but readable

       ;; :email
       ;;(mu4e +org +gmail)
       ;; (notmuch +org)

       :app
       ;; calendar
       ;; emms
       (rss +org +youtube)        ; emacs as an RSS reader

       :config
       ;; literate ; use manually
       (default +bindings +smartparens)
       )
